Steal code and rebrand
spacebarchat/martian pull request #4
Opened 2022-02-27 17:52 UTC by HeadTriXz

Fixes Issue #1

2022-02-27 20:16 UTC, coolcalcacol commented
LGTM!

2022-02-28 07:30 UTC, erkinalp requested changes

2022-02-28 07:30 UTC, erkinalp commented on CONTRIBUTING.md
> +- Discuss additions/changes with us [on Discord](https://abal.moe/Martian/invite) before working on them
```suggestion
- Discuss additions/changes with us [on Discord](https://discord.gg/Q4mRZX4T) before working on them
```

2022-02-28 07:30 UTC, erkinalp commented on README.md
> +<p align="center">A Node.js wrapper for interfacing with Discord.</p>
```suggestion
<p align="center">A Node.js wrapper for interfacing with Fosscord.</p>
```

2022-02-28 07:30 UTC, erkinalp commented on README.md
> +You will need NodeJS 10.4+. If you need voice support you will also need Python 2.7 and a C++ compiler. Refer to [the Getting Started section of the docs](https://www.youtube.com/watch?v=d1YBv2mWll0)
```suggestion
You will need NodeJS 10.4+. If you need voice support you will also need Python 2.7 and a C++ compiler. Refer to [upstream docs](https://abal.moe/Eris/docs) for more details.
```

2022-02-28 07:30 UTC, erkinalp commented on README.md
> +More examples can be found in [the examples folder](https://www.youtube.com/watch?v=d1YBv2mWll0).
```suggestion
More examples can be found in [the examples folder](https://github.com/fosscord/martian/tree/master/examples).
```

2022-02-28 07:30 UTC, erkinalp commented on README.md
> +- [The NPM package webpage](https://www.youtube.com/watch?v=d1YBv2mWll0) is, well, the webpage for the NPM package.
```suggestion
- [The official Martian server](https://discord.gg/RYPfhtX2ty) is the best place to get support.
- [The GitHub repo](https://github.com/fosscord/martian) is where development primarily happens.
```

2022-02-28 07:30 UTC, erkinalp commented on package.json
> +    "url": "https://www.youtube.com/watch?v=d1YBv2mWll0"
```suggestion
    "url": "https://github.com/fosscord/martian"
```

2022-02-28 07:30 UTC, erkinalp commented on package.json
>    "description": "A NodeJS Discord library",
```suggestion
  "description": "A NodeJS Fosscord library",
```

2022-02-28 07:30 UTC, erkinalp commented on package.json
> +  "homepage": "https://www.youtube.com/watch?v=d1YBv2mWll0",
```suggestion
  "homepage": "https://github.com/fosscord/martian",
```

2022-02-28 07:32 UTC, closed without merging